version: '3.4'
services:
  besu_node:
    image: hyperledger/besu:latest
    command: ["--network=goerli",
              "--sync-mode=X_SNAP",
              "--data-path=/var/lib/besu",
              "--data-storage-format=BONSAI",
              "--host-allowlist=*",
              "--rpc-http-enabled",
              "--rpc-http-cors-origins=*",
              "--fast-sync-min-peers=1",
              "--metrics-enabled=true",
              "--metrics-host=0.0.0.0",
              "--rpc-http-api=ADMIN,ETH,NET,WEB3",
              "--engine-host-allowlist=*",
              "--engine-jwt-secret=/secret/jwtsecret.hex"]
    volumes:
      - /home/ubuntu/.besu/mainnet:/var/lib/besu
      - /home/ubuntu/besu/:/secret
    ports:
      # Map the p2p port(30303) and RPC HTTP port(8545)
      - "8545:8545"
      - "30303:30303/tcp"
      - "30303:30303/udp"

  lighthouse-bn:
    image: sigp/lighthouse:latest
    volumes:
      - /home/ubuntu/.lighthouse:/root/.lighthouse
      - /home/ubuntu/besu/:/secret
    command: ["lighthouse",
              "beacon",
              "--network=prater",
              "--http",
              "--http-address=0.0.0.0",
              "--execution-endpoint=http://besu_node:8551",
              "--execution-jwt=/secret/jwtsecret.hex"]
    ports:
      - "9000:9000"
      - "5052:5052"